version: 2

before:
  hooks:
    - go run ./cmd/sy generate --check

builds:
  - id: seshy
    main: ./cmd/sy
    binary: sy
    env:
      - CGO_ENABLED=0
    flags: [-trimpath]
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

archives:
  - id: seshy
    ids: [seshy]
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - src: completions/*
        dst: completions
      - src: schema/*.json
        dst: schema
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

changelog:
  use: github-native
