package cmd

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
)

var initCmd = &cobra.Command{
	Use:   "init <shell>",
	Short: "Print shell integration code",
	Long: `Print shell integration code for your shell.

Add to your shell config:
  eval "$(sy init zsh)"   # zsh
  eval "$(sy init bash)"  # bash
  sy init fish | source   # fish
  sy init nu | save --force ~/.config/nushell/vendor/autoload/sy.nu

With shell integration active, "sy <name>" will cd into the session directory
using greedy matching. Commands and aliases always run as commands. Use
"sy --greedy <name>" to resolve a session whose name conflicts with one.`,
	Args:      cobra.ExactArgs(1),
	ValidArgs: []string{"zsh", "bash", "fish", "nu"},
	RunE: func(cmd *cobra.Command, args []string) error {
		switch args[0] {
		case "fish":
			generated, err := renderShellIntegration("fish", fishIntegration)
			if err != nil {
				return err
			}
			fmt.Print(generated)
		case "nu":
			generated, err := generatedCompletion("nu")
			if err != nil {
				return err
			}
			fmt.Println(generated)
		case "zsh", "bash":
			generated, err := renderShellIntegration(args[0], map[string]string{
				"zsh":  zshIntegration,
				"bash": bashIntegration,
			}[args[0]])
			if err != nil {
				return err
			}
			fmt.Print(generated)
		default:
			return fmt.Errorf("unsupported shell %q — supported: zsh, bash, fish, nu", args[0])
		}
		return nil
	},
}

const zshIntegration = `# seshy shell integration — generated by sy init zsh
function sy() {
  local _p
  if [[ $# -eq 1 ]] && [[ "${1}" != -* ]]; then
    case "${1}" in
      {{ join .Reserved "|" }}) command sy "$@"; return ;;
    esac
    if _p=$(command sy --greedy "${1}" 2>/dev/null) && [[ -n "${_p}" ]]; then
      cd "${_p}"
      return
    fi
  fi
  command sy "$@"
}
`

const bashIntegration = `# seshy shell integration — generated by sy init bash
sy() {
  local _p
  if [[ $# -eq 1 ]] && [[ "${1}" != -* ]]; then
    case "${1}" in
      {{ join .Reserved "|" }}) command sy "$@"; return ;;
    esac
    if _p=$(command sy --greedy "${1}" 2>/dev/null) && [[ -n "${_p}" ]]; then
      cd "${_p}"
      return
    fi
  fi
  command sy "$@"
}
`

const fishIntegration = `# seshy shell integration — generated by sy init fish
function sy
  if test (count $argv) -eq 1; and not string match -q -- '-*' $argv[1]
    switch $argv[1]
      case {{ join .Reserved " " }}
        command sy $argv
        return
    end
    set -l _p (command sy --greedy $argv[1] 2>/dev/null)
    if test -n "$_p"
      cd $_p
      return
    end
  end
  command sy $argv
end
`

const nushellBody = ` {
  if $greedy != null {
    return (^sy --greedy $greedy ...$args)
  }
  if (($args | length) == 1) and (not ($args.0 | str starts-with "-")) and ($args.0 not-in [{{ quote .Reserved }}]) {
    let resolved = (^sy --greedy $args.0 | complete)
    if ($resolved.exit_code == 0) and (not ($resolved.stdout | str trim | is-empty)) {
      cd ($resolved.stdout | str trim)
      return
    }
  }
  ^sy ...$args
}
`

type integrationData struct {
	Reserved []string
}

func renderShellIntegration(name, source string) (string, error) {
	tmpl, err := template.New(name).Funcs(template.FuncMap{
		"join":  strings.Join,
		"quote": quoteNushellValues,
	}).Parse(source)
	if err != nil {
		return "", err
	}
	var output bytes.Buffer
	if err := tmpl.Execute(&output, integrationData{Reserved: rootInvocationNames()}); err != nil {
		return "", err
	}
	return output.String(), nil
}

func rootInvocationNames() []string {
	seen := map[string]struct{}{}
	for _, command := range rootCmd.Commands() {
		seen[command.Name()] = struct{}{}
		for _, alias := range command.Aliases {
			seen[alias] = struct{}{}
		}
	}
	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func quoteNushellValues(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = fmt.Sprintf("%q", value)
	}
	return strings.Join(quoted, " ")
}

func init() {
	rootCmd.AddCommand(initCmd)
}
